export enum ActionTypes {
  SET_IMAGES,
  SELECT_IMAGE,
  ADD_MATCH,
  ADD_POINT,
  CHANGE_PLAYER,
  UNSELECT_IMAGES,
  REDUCE_MATCHES_LEFT,
  SET_MATCH_TOTAL,
  ADD_FEEDBACK_MSG,
  RESET_GAME,
  CHANGE_THEME,
  INCREMENT_LOADED_IMAGES
}
