export const animalsData = [
  'elephant',
  'fish',
  'cheetah',
  'fox',
  'frog',
  'penguin',
  'sheep',
  'walrus',
  'giraffe',
  'zebra'
  // "../../assets/images/animals/cheetah.jpg",
	// "../../assets/images/animals/elephant.jpg",
	// "../../assets/images/animals/fish.jpg",
	// "../../assets/images/animals/fox.jpg",
	// "../../assets/images/animals/frog.jpg",
	// "../../assets/images/animals/penguin.jpg",
	// "../../assets/images/animals/sheep.jpg",
	// "../../assets/images/animals/walrus.jpg",
	// "../../assets/images/animals/giraffe.jpg",
	// "../../assets/images/animals/zebra.jpg",
]