export const SET_IMAGES = 'SET_IMAGES'
export const SELECT_IMAGE = 'SELECT_IMAGE'
export const ADD_MATCH = 'ADD_MATCH'
export const ADD_POINT = 'ADD_POINT'
export const CHANGE_PLAYER = 'CHANGE_PLAYER'
